global:
  smtp_smarthost: '${SMTP_HOST:smtp.gmail.com:587}'
  smtp_from: '${SMTP_FROM:alerts@codesage.com}'
  smtp_auth_username: '${SMTP_USERNAME:your-email@gmail.com}'
  smtp_auth_password: '${SMTP_PASSWORD:your-app-password}'

route:
  group_by: ['alertname', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email'
  routes:
    - match:
        severity: critical
      receiver: 'critical-email'
      continue: true
    - match:
        type: predictive
      receiver: 'predictive-alerts'
      group_wait: 30s
      group_interval: 30s
      repeat_interval: 4h
    - match:
        type: anomaly
      receiver: 'anomaly-alerts'
      group_wait: 5s
      group_interval: 5s
      repeat_interval: 30m

receivers:
  - name: 'email'
    email_configs:
      - to: '${ALERT_EMAIL:admin@codesage.com}'
        subject: 'CodeSage MCP Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Service: {{ .Labels.service }}
          Runbook: {{ .Annotations.runbook_url }}
          Timestamp: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}

  - name: 'critical-email'
    email_configs:
      - to: '${CRITICAL_ALERT_EMAIL:critical@codesage.com}'
        subject: 'CRITICAL CodeSage MCP Alert: {{ .GroupLabels.alertname }}'
        body: |
          🚨 CRITICAL ALERT 🚨

          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Service: {{ .Labels.service }}
          Runbook: {{ .Annotations.runbook_url }}
          Timestamp: {{ .StartsAt.Format "2006-01-02 15:04:05" }}

          Immediate action required!
          {{ end }}

  - name: 'predictive-alerts'
    email_configs:
      - to: '${PREDICTIVE_ALERT_EMAIL:ops@codesage.com}'
        subject: 'Predictive Alert: {{ .GroupLabels.alertname }}'
        body: |
          🔮 PREDICTIVE ALERT 🔮

          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Service: {{ .Labels.service }}
          Type: {{ .Labels.type }}
          Runbook: {{ .Annotations.runbook_url }}
          Timestamp: {{ .StartsAt.Format "2006-01-02 15:04:05" }}

          This is a predictive alert. Take preventive action.
          {{ end }}

  - name: 'anomaly-alerts'
    email_configs:
      - to: '${ANOMALY_ALERT_EMAIL:devops@codesage.com}'
        subject: 'Anomaly Detected: {{ .GroupLabels.alertname }}'
        body: |
          🤖 ANOMALY DETECTED 🤖

          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Service: {{ .Labels.service }}
          Type: {{ .Labels.type }}
          Runbook: {{ .Annotations.runbook_url }}
          Timestamp: {{ .StartsAt.Format "2006-01-02 15:04:05" }}

          Investigate anomaly immediately.
          {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service']
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'info'
    equal: ['alertname', 'service']
  - source_match:
      type: 'anomaly'
    target_match:
      type: 'predictive'
    equal: ['service']
